export const QUIZ_TEXT = {
    "zh-TW": {
        q1: "遇到新目標你通常先？",
        q1a: "立刻開始做，邊做邊調整",
        q1b: "先想清楚方向與風險",
        q1c: "先確認感受與直覺是不是對的",
        q1d: "先排節奏，穩穩做",

        q2: "你卡住最常因為？",
        q2a: "熱度退太快，動力跟不上",
        q2b: "想太多，怕做錯",
        q2c: "情緒起伏大，容易內耗",
        q2d: "缺乏規律，難以持續",

        q3: "你最需要的支持是？",
        q3a: "有人推我一把，讓我動起來",
        q3b: "幫我釐清優先順序與方向",
        q3c: "被理解、被安定情緒",
        q3d: "協助我建立可執行的習慣",

        q4: "你偏好的提醒語氣？",
        q4a: "直接明確：現在就做一小步",
        q4b: "理性拆解：一步一步來",
        q4c: "溫柔陪伴：我陪你慢慢走",
        q4d: "簡潔指令：給我今天要做什麼",

        q5: "你一天最容易完成小行動的時間？",
        q5a: "早上",
        q5b: "中午",
        q5c: "晚上",
        q5d: "不固定",

        q6: "你比較做得下去的微行動是？",
        q6a: "社交型（訊息、連結、互動）",
        q6b: "身體型（走路、運動、呼吸）",
        q6c: "整理規劃型（清單、整理環境）",
        q6d: "學習輸出型（讀、寫、練習）",

        q7: "你現在怎麼看待「顯化」？",
        q7a: "我相信它，想認真練",
        q7b: "半信半疑，但願意試看看",
        q7c: "我把它當作習慣與心態訓練",
        q7d: "我比較看感覺，但希望更穩定",

        q8: "30 天後你最想看到的改變？",
        q8a: "更有自信",
        q8b: "更有行動力",
        q8c: "更穩定、有節奏",
        q8d: "更清楚方向、少內耗",
    },
    en: {
        q1: "When you start a new goal, what do you do first?",
        q1a: "Start immediately and adjust along the way",
        q1b: "Think it through and assess risks",
        q1c: "Check how it feels—trust your intuition",
        q1d: "Set a steady plan and follow a rhythm",

        q2: "You get stuck most often because…",
        q2a: "Motivation fades too fast",
        q2b: "Overthinking and fear of mistakes",
        q2c: "Emotional ups and downs drain you",
        q2d: "Lack of consistency and structure",

        q3: "The support you need most is…",
        q3a: "A push that gets me moving",
        q3b: "Clarity on priorities and direction",
        q3c: "Emotional grounding and understanding",
        q3d: "Help building doable habits",

        q4: "What tone works best for reminders?",
        q4a: "Direct: take one small step now",
        q4b: "Rational: break it down",
        q4c: "Gentle: I’m with you",
        q4d: "Minimal: just tell me what to do",

        q5: "When are you most likely to do a micro-action?",
        q5a: "Morning",
        q5b: "Midday",
        q5c: "Evening",
        q5d: "Varies",

        q6: "Which micro-actions are easiest for you to keep?",
        q6a: "Social (message, connect, interact)",
        q6b: "Body (walk, move, breathe)",
        q6c: "Organize (plan, tidy, list)",
        q6d: "Learn/Output (read, write, practice)",

        q7: "How do you see “manifesting” right now?",
        q7a: "I believe in it and want to train it",
        q7b: "Not sure, but I’ll try",
        q7c: "I treat it as mindset + habit training",
        q7d: "I’m feeling-based, but want more stability",

        q8: "In 30 days, what change do you want most?",
        q8a: "More confidence",
        q8b: "More action and momentum",
        q8c: "More stability and rhythm",
        q8d: "More clarity, less mental noise",
    },
};